# Generated by Django 6.0.2 on 2026-03-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_tarjeta',
            field=models.CharField(help_text='Número de tarjeta (16 dígitos, solo números)', max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto (mínimo 3 caracteres)', max_length=100, unique=True),
        ),
    ]
