# Generated by Django 6.0.2 on 2026-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_alter_categoria_nombre_alter_cliente_numero_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Monto total de la compra', max_digits=10),
            preserve_default=False,
        ),
    ]
