# Generated by Django 6.0.2 on 2026-03-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0003_compra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Spain 2026', max_length=300, unique=True, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='1234567', help_text='Número de teléfono (solo dígitos, entre 7 y 15 dígitos)', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
