# Generated by Django 6.0.2 on 2026-03-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0004_cliente_direccion_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tienda_app.cliente'),
            preserve_default=False,
        ),
    ]
