# Generated by Django 6.0.2 on 2026-03-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0005_remove_compra_usuario_compra_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.ForeignKey(default=1, help_text='Moneda en la que se realizó la compra', on_delete=django.db.models.deletion.PROTECT, to='tienda_app.moneda'),
            preserve_default=False,
        ),
    ]
