# Generated by Django 6.0.2 on 2026-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0006_compra_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de la compra', max_digits=15),
        ),
    ]
